name: Publish to docker

on:    
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Publish to Registry (Latest Release)
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: shadow046/online_parking/online_parking:latest
        username: ${{ github.actor }}
        password: ${{ secrets.GITPASS }}
        registry: ghcr.io

    - name: Publish to Registry (Version Release)
      uses: elgohr/Publish-Docker-Github-Action@v4
      with:
        name: shadow046/online_parking/online_parking
        username: ${{ github.actor }}
        password: ${{ secrets.GITPASS }}
        registry: ghcr.io
        tag_names: true
